### PR TITLE
Log csv task

### PR DESCRIPTION
**Pull request by haoransun93**
finished logging to csv, with assorted unit tests in place.

-only issue left to resolve is if it is possible to have an end character for every binary entry to be able to differentiate when a binary entry begins or ends.

### CODE REVIEW

**Comment by SpaceShawn** [comment]
I see your point about the terminating character, however what naturally arises is the issue that the character chosen could arise in the binary data and be picked up in the wrong place. I would tend to prefer a length byte in the entry header, but I'm not sure that can be accomplished without changing all the log calls elsewhere in the project.  

Can you propose a character or sequence of characters or a solution otherwise? I'd like that to be resolved in the pull request

Thanks Jack!

**Comment by SpaceShawn** [comment]
Actually I now recall that binary logging uses a fixed frame size, allowing two bytes for data storage. Since all binary data entries should be the same length you should not need a terminating character to tell them apart, correct? You can just take the sizeof the struct defined in the header file     
```
typedef struct  {
        time_t 	    date_time;
        uint8_t     subsystem;
        uint8_t	    priority;
        uint16_t	data;
    } BinaryLogEntry;
```
Please let me know if this addresses the problem

**Comment by haoransun93** [comment]
For reading the binary, I used the sizeof for this. If it is guaranteed that the binary entries will always be the same size, then it's fine!

I'm just worried that if the binary entry is supposed to be say 8 bytes, then one entry of 7 bytes would wreck everything. if there's no chance of that happening then everything is good!

**Comment by haoransun93** [comment]
Ah, one more thing, I forgot to make a small chance, the ascii text has the "/r/n" at the end of it. it needs to be taken out of the string before writing to csv.

I'll fix that this weekend!

**Comment by SpaceShawn** [comment]
Okay I understand. In that case I think a terminating or identifying byte
for the data frame would be a good idea to avoid such a situation.

Can you please propose something for implementation when you look at the
ASCII issue?

**Pull request merged**
